[build]
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "penpot/"
  
  # Default build command
  command = "bun run build:penpot"

[build.environment]
  NODE_VERSION = "20"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
